ssh and a bunch of other stuff

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-BASEDIR="$(dirname `readlink -f $0`)"
+BASEDIR="$(readlink -f `dirname  $0`/..)";
 
 usage() {
     cat <<END_OF_USAGE >&2
@@ -17,9 +17,14 @@ END_OF_USAGE
 }
 
 run-now() {
-    SCRIPTS=$(command find $BASEDIR -maxdepth 1 -regex '^.*\/[0-9][0-9][a-zA-Z-]+\.sh$' -type f -print | command sort )
+    SCRIPTS=$(command find $BASEDIR/scripts -maxdepth 1 -regex '^.*\/[0-9][0-9][a-zA-Z-]+\.sh$' -type f -print | command sort )
     for SCRIPT in $SCRIPTS; do
-        /bin/bash $SCRIPT up
+        echo "Running: $SCRIPT"
+        /bin/bash $SCRIPT "$BASEDIR"
+        if [ $? -eq 255 ]; then
+            echo "Error 255 encountered in script '$SCRIPT'"
+            exit 255
+        fi
     done
 }
 
